plugins {
    id 'java'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group = 'us.florent'
version = '4.5'

repositories {
    mavenCentral()
}

jar {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    manifest {
        attributes 'Main-Class': 'us.florent.GenReef4'
    }
    from {
        configurations
                .runtimeClasspath
                .collect {
                    it.isDirectory() ? it : zipTree(it)
                }
    }
}

javafx {
    version = '26'
    modules = ['javafx.controls']
}

dependencies {
    implementation 'org.json:json:20260814'
    implementation 'org.mongodb:mongodb-driver-sync:5.13.+'
    implementation 'org.slf4j:slf4j-api:2.0+'
    implementation 'org.slf4j:slf4j-simple:2.0+'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.22+'
    implementation 'org.junit.jupiter:junit-jupiter:6+'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:6+'
    testImplementation 'org.junit.jupiter:junit-jupiter-engine:6+'
    testImplementation 'org.mockito:mockito-core:5+'
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

test {
    useJUnitPlatform()
}
